// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifravdieobvwcwlypput.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmcmF2ZGllb2J2d2N3bHlwcHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMTg3NTksImV4cCI6MjA1NTU5NDc1OX0.4UowNOZxOfaVAknXssC58jOUlc_aAl2c4U1Dl7Fvf1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);